build:
    environment:
        php:
            version: '7.1'
    tests:
        override:
            -
                command: 'bin/phpunit --configuration=tests/phpunit.xml --coverage-clover=clover.xml'
                coverage:
                    file: 'clover.xml'
                    format: 'php-clover'

checks:
    php:
        duplication: false

filter:
    paths:
        - 'src/*'
