git:
    depth: 1

cache:
    directories:
        - $HOME/.composer/cache

sudo: false

language: php

notifications:
    email: false

php:
    - 7.1

before_install:
    - (phpenv config-rm xdebug.ini || exit 0)
    - composer self-update

install:
    - composer install --no-scripts
    - cp config/parameters.yml.dist config/parameters.yml

script:
    - bin/phing check
