application.initialized:
  - {service: app.jira_service, action: onApplicationInitialized}
jira.ticket.mapped:
  - {service: app.bitbucket_service, action: onJiraTicketMapped}
  - {service: app.existing_tickets_index_service, action: onJiraTicketMapped}
  - {service: app.ticket_service_repository, action: onJiraTicketMapped}
bitbucket.ticked.mapped:
  - {service: app.ticket_service_repository, action: onBitbucketTicketMapped}
ticket.dir.indexed:
  - {service: app.ticket_service_repository, action: onTicketDirIndexed}