parameters:
  config.path: "config/config.yml"
  event.listener.config.path: "config/event.listener.yml"
  application.config: "@=service('app.configuration').get()"

services:
  app.logger:
    class: \SimpleLogger\Stdout

  app.query_repository:
    class: \Pvg\Application\Module\Jira\QueryRepository
    public: false

  app.jira_service_factory:
    class: \Pvg\Application\Module\Jira\Factory\JiraServiceFactory
    public: false

  app.jira_service:
    class: \Pvg\Application\Module\Jira\ExternalLibraryJiraService
    factory: 'app.jira_service_factory:create'
    arguments: ["%application.config%",
                "@app.event_dispatcher",
                "@app.logger",
                "@app.query_repository"]

  app.configuration:
    class: \Pvg\Application\Configuration\ConfigReader
    arguments:
      - "@app.file_locator"
      - "%config.path%"
      - "%event.listener.config.path%"
      - "@app.event_dispatcher"
      - "@app.logger"
    calls:
      - method: init
      
  deploy_test_branch_command:
    class: \Pvg\Command\DeployTestBranchCommand
    arguments:
      - "%application.config%"
      - "@app.logger"
      - "@app.event_dispatcher"

