parameters:
  config.path: "config/config.yml"
  event.listener.config.path: "config/event.listener.yml"
  application.config: "@=service('app.configuration').get()"

services:
  app.logger:
    class: \SimpleLogger\Stdout

  app.jira_service:
    class: \Pvg\Application\Jira\ExternalLibraryJiraService
    arguments:
      - "@app.jira_config_factory"
      - "@app.logger"
      - "@app.event_dispatcher"
      - "@app.query_repository"

  app.query_repository:
    class: \Pvg\Application\Jira\QueryRepository
    public: false

  app.jira_config_factory:
    class: \Pvg\Application\Jira\Factory\JiraConfigFactory
    arguments:
      - "%application.config%"

  app.tickets_filter:
    class: \Pvg\Application\Jira\TicketInfoFilter
    
  app.configuration:
    class: \Pvg\Application\Configuration\ConfigReader
    arguments:
      - "@app.file_locator"
      - "%config.path%"
      - "%event.listener.config.path%"
      - "@app.event_dispatcher"
      - "@app.logger"
    calls:
      - method: init
      
  deploy_test_branch_command:
    class: \Pvg\Command\DeployTestBranchCommand
    arguments:
      - "%application.config%"
      - "@app.logger"
      - "@app.event_dispatcher"

