parameters:
  config.path: "config/config.yml"
  event.listener.config.path: "config/event.listener.yml"
  application.config: "@=service('app.configuration').get()"

services:
  app.logger:
    class: \SimpleLogger\Stdout

  app.jira_service:
    class: \Pvg\Application\Jira\ExternalLibraryJiraService
    arguments:
      - "%application.config%"
      - "@app.logger"
      - "@app.event_dispatcher"
    
  app.configuration:
    class: \Pvg\Application\Configuration\ConfigReader
    arguments:
      - "@app.file_locator"
      - "%config.path%"
      - "%event.listener.config.path%"
      - "@app.event_dispatcher"
      - "@app.logger"
    calls:
      - method: init
      
  deploy_test_branch_command:
    class: \Pvg\Command\DeployTestBranchCommand
    arguments:
      - "%application.config%"
      - "@app.logger"
      - "@app.event_dispatcher"

